/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Ch */

#ifndef _Included_Ch
#define _Included_Ch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Ch
 * Method:    myimprt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Ch_myimprt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
